payoff_b <- matrix(c(100,40,-20,60,60,60,20,100,80), nrow=3, byrow=TRUE)
alpha <- 0.6
cat("Benefit Maximax:", apply(payoff_b,1,max), "\n")
cat("Benefit Maximin:", apply(payoff_b,1,min), "\n")
cat("Benefit Laplace:", rowMeans(payoff_b), "\n")
cat("Benefit Hurwicz:", alpha*apply(payoff_b,1,max)+(1-alpha)*apply(payoff_b,1,min), "\n")
regret_b <- sweep(matrix(apply(payoff_b,2,max), nrow=3, ncol=3, byrow=TRUE), 1:2, payoff_b, "-")
cat("Benefit regret:\n"); print(regret_b)
cat("Benefit minimax regret:", apply(regret_b,1,max), "\n")

payoff_c <- matrix(c(20,50,80,40,40,40,80,30,20), nrow=3, byrow=TRUE)
cat("\nCost Minimin:", apply(payoff_c,1,min), "\n")
cat("Cost Minimax:", apply(payoff_c,1,max), "\n")
cat("Cost Laplace:", rowMeans(payoff_c), "\n")
cat("Cost Hurwicz:", alpha*apply(payoff_c,1,min)+(1-alpha)*apply(payoff_c,1,max), "\n")
regret_c <- sweep(payoff_c, 2, apply(payoff_c,2,min), "-")
cat("Cost regret:\n"); print(regret_c)
cat("Cost minimax regret:", apply(regret_c,1,max), "\n")
